# kafka-manager镜像：https://hub.docker.com/r/sheepkiller/kafka-manager

# 1.镜像支持的环境变量及默认值：
# KAFKA_VERSION = 2.4.0
# KAFKA_ZOOKEEPER_CONNECT = 
# KAFKA_PORT =
# KAFKA_ADVERTISED_PORT = 
# KAFKA_LISTENERS =
# KAFKA_ADVERTISED_LISTENERS =
# KAFKA_BROKER_ID =
# BROKER_ID_COMMAND =
# KAFKA_LOG_DIRS = /kafka/kafka-logs-$HOSTNAME
# KAFKA_HEAP_OPTS = 
# ------------------------------------------------------------------

# 2.镜像目录结构及配置文件
# (1)入口文件：
# $ find / -name "start-kafka.sh"
# /usr/bin/start-kafka.sh
# (2)kafka目录：/opt/kafka
# 配置文件中的配置项通过环境变量可改变
# ------------------------------------------------------------------

# 3.kafka-manager安装
version: '3'
services:
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    restart: always
	ports:
	  - "9000:9000"
    environment:
      ZK_HOSTS: zoo1:2181,zoo2:2182
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    